// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoppingMall.Models
{
    public partial class Catalog
    {
        public Catalog()
        {
            InverseParent = new HashSet<Catalog>();
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentId { get; set; }

        public virtual Catalog Parent { get; set; }
        public virtual ICollection<Catalog> InverseParent { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}