// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoppingMall.Models
{
    public partial class Product
    {
        public Product()
        {
            Cart = new HashSet<Cart>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public decimal UnitPrice { get; set; }
        public int Count { get; set; }
        public int CatalogId { get; set; }
        public string PicturePath { get; set; }

        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}