// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoppingMall.Models
{
    public partial class User
    {
        public User()
        {
            Bill = new HashSet<Bill>();
            Cart = new HashSet<Cart>();
        }

        public Guid Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Bill> Bill { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}